name: .NET Core Desktop

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Duo/Duo.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: DuoTests/DuoTests.csproj      # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Set up .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies using dotnet restore (ensures all NuGet packages are restored)
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    # Clean the build output directory (optional)
    - name: Clean the build
      run: dotnet clean $env:Solution_Name --configuration ${{ matrix.configuration }}

    # Build the project
    - name: Build the project
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Run unit tests
      run: dotnet test $env:Test_Project_Path --configuration ${{ matrix.configuration }}

